[package]
name = "sncast_scripts"
version = "0.1.0"

[dependencies]
starknet = "2.8.2"
sncast_std = "0.30.0"
revenantscholar_presets = { path = "../" }
revenantscholar_testing = { path = "../" }

[lib]
sierra = true
casm = true

[[target.starknet-contract]]
sierra = true
casm = true
build-external-contracts = [
    "revenantscholar_presets::account::AccountUpgradeable",
    "revenantscholar_presets::erc20::ERC20Upgradeable",
    "revenantscholar_presets::erc721::ERC721Upgradeable",
    "revenantscholar_presets::erc1155::ERC1155Upgradeable",
    "revenantscholar_presets::eth_account::EthAccountUpgradeable",
    "revenantscholar_presets::vesting::VestingWallet",
]
