[workspace]
members = [
    "packages/access",
    "packages/account",
    "packages/finance",
    "packages/governance",
    "packages/introspection",
    "packages/merkle_tree",
    "packages/presets",
    "packages/security",
    "packages/token",
    "packages/upgrades",
    "packages/utils",
    "packages/testing",
    "packages/test_common",
]

[package]
name = "revenantscholar"
readme = "README.md"
version.workspace = true
keywords.workspace = true

[workspace.package]
version = "0.19.0"
edition = "2024_07"
cairo-version = "2.8.4"
scarb-version = "2.8.4"
authors = ["OpenZeppelin Community <maintainers@openzeppelin.org>"]
description = "OpenZeppelin Contracts written in Cairo for Starknet, a decentralized ZK Rollup"
documentation = "https://docs.openzeppelin.com/contracts-cairo"
repository = "https://github.com/OpenZeppelin/cairo-contracts"
license-file = "LICENSE"
keywords = [
    "openzeppelin",
    "starknet",
    "contracts",
    "security",
    "standards"
]

[workspace.dependencies]
assert_macros = "2.8.4"
starknet = "2.8.4"
snforge_std = "0.31.0"

[dependencies]
starknet.workspace = true
revenantscholar_access = { path = "packages/access" }
revenantscholar_account = { path = "packages/account" }
revenantscholar_finance = { path = "packages/finance" }
revenantscholar_governance = { path = "packages/governance" }
revenantscholar_introspection = { path = "packages/introspection" }
revenantscholar_merkle_tree = { path = "packages/merkle_tree" }
revenantscholar_presets = { path = "packages/presets" }
revenantscholar_security = { path = "packages/security" }
revenantscholar_token = { path = "packages/token" }
revenantscholar_upgrades = { path = "packages/upgrades" }
revenantscholar_utils = { path = "packages/utils" }

[dev-dependencies]
snforge_std.workspace = true
revenantscholar_test_common = { path = "packages/test_common" }
revenantscholar_testing = { path = "packages/testing" }

[lib]

[[target.starknet-contract]]
allowed-libfuncs-list.name = "experimental"
sierra = true
casm = false

[workspace.tool.fmt]
sort-module-level-items = true

[tool]
fmt.workspace = true

[profile.dev.cairo]
unstable-add-statements-functions-debug-info = true
unstable-add-statements-code-locations-debug-info = true
inlining-strategy= "avoid"
