
[package]
name = "revenantscholar_upgrades"
readme = "README.md"
keywords = [
    "openzeppelin",
    "starknet",
    "contracts",
    "upgrades"
]
version.workspace = true
edition.workspace = true
cairo-version.workspace = true
scarb-version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
repository.workspace = true
license-file.workspace = true

[tool]
fmt.workspace = true

[dependencies]
starknet.workspace = true

[dev-dependencies]
assert_macros.workspace = true
snforge_std.workspace = true
revenantscholar_testing = { path = "../testing" }
revenantscholar_test_common = { path = "../test_common" }

[lib]

[[target.starknet-contract]]
allowed-libfuncs-list.name = "experimental"
sierra = true
casm = false

[[test]]
name = "revenantscholar_upgrades_unittest"
build-external-contracts = [
    "revenantscholar_test_common::mocks::upgrades::UpgradesV1",
    "revenantscholar_test_common::mocks::upgrades::UpgradesV2",
]
