[package]
name = "revenantscholar_finance"
readme = "README.md"
keywords = [
    "openzeppelin",
    "starknet",
    "contracts",
    "finance",
    "vesting"
]
version.workspace = true
edition.workspace = true
cairo-version.workspace = true
scarb-version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
repository.workspace = true
license-file.workspace = true

[tool]
fmt.workspace = true

[dependencies]
starknet.workspace = true
revenantscholar_access = { path = "../access" }
revenantscholar_token = { path = "../token" }

[dev-dependencies]
snforge_std.workspace = true
revenantscholar_testing = { path = "../testing" }
revenantscholar_test_common = { path = "../test_common" }

[lib]

[[target.starknet-contract]]
allowed-libfuncs-list.name = "experimental"
sierra = true
casm = false

[[test]]
name = "revenantscholar_finance_unittest"
build-external-contracts = [
    "revenantscholar_test_common::mocks::vesting::LinearVestingMock",
    "revenantscholar_test_common::mocks::vesting::StepsVestingMock",
    "revenantscholar_test_common::mocks::vesting::ERC20OptionalTransferPanicMock",
]
