[package]
name = "openzeppelin_test_common"
readme = "README.md"
version.workspace = true
edition.workspace = true
cairo-version.workspace = true
scarb-version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
repository.workspace = true
license-file.workspace = true
keywords.workspace = true

[tool]
fmt.workspace = true

[dependencies]
starknet.workspace = true
snforge_std.workspace = true
openzeppelin_upgrades = { path = "../upgrades" }
revenantscholar_access = { path = "../access" }
revenantscholar_account = { path = "../account" }
openzeppelin_finance = { path = "../finance" }
revenantscholar_introspection = { path = "../introspection" }
openzeppelin_security = { path = "../security" }
revenantscholar_token = { path = "../token" }
openzeppelin_testing = { path = "../testing" }
revenantscholar_utils = { path = "../utils" }
openzeppelin_governance = { path = "../governance" }

[lib]

[[target.starknet-contract]]
allowed-libfuncs-list.name = "experimental"
sierra = true
casm = false
