[package]
name = "revenantscholar_account"
readme = "README.md"
keywords = [
    "openzeppelin",
    "starknet",
    "contracts",
    "standards",
    "account"
]
version.workspace = true
edition.workspace = true
cairo-version.workspace = true
scarb-version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
repository.workspace = true
license-file.workspace = true

[tool]
fmt.workspace = true

[dependencies]
starknet.workspace = true
revenantscholar_introspection = { path = "../introspection" }
revenantscholar_utils = { path = "../utils" }

[dev-dependencies]
assert_macros.workspace = true
snforge_std.workspace = true
revenantscholar_testing = { path = "../testing" }
revenantscholar_test_common = { path = "../test_common" }

[lib]

[[target.starknet-contract]]
allowed-libfuncs-list.name = "experimental"
sierra = true
casm = false

[[test]]
name = "revenantscholar_account_unittest"
build-external-contracts = [
    "revenantscholar_test_common::mocks::account::DualCaseAccountMock",
    "revenantscholar_test_common::mocks::account::DualCaseEthAccountMock",
    "revenantscholar_test_common::mocks::src9::SRC9AccountMock",
    "revenantscholar_test_common::mocks::simple::SimpleMock",
]
