[package]
name = "revenantscholar_presets"
readme = "README.md"
keywords = [
    "openzeppelin",
    "starknet",
    "contracts",
    "presets"
]
version.workspace = true
edition.workspace = true
cairo-version.workspace = true
scarb-version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
repository.workspace = true
license-file.workspace = true

[tool]
fmt.workspace = true

[dependencies]
starknet.workspace = true
revenantscholar_access = { path = "../access" }
revenantscholar_account = { path = "../account" }
revenantscholar_finance = { path = "../finance" }
revenantscholar_introspection = { path = "../introspection" }
revenantscholar_token = { path = "../token" }
revenantscholar_upgrades = { path = "../upgrades" }
revenantscholar_utils = { path = "../utils" }

[dev-dependencies]
assert_macros.workspace = true
snforge_std.workspace = true
revenantscholar_testing = { path = "../testing" }
revenantscholar_test_common = { path = "../test_common" }

[lib]

[[target.starknet-contract]]
allowed-libfuncs-list.name = "experimental"
sierra = true
casm = false

[[test]]
name = "revenantscholar_presets_unittest"
build-external-contracts = [
    "revenantscholar_test_common::mocks::account::DualCaseAccountMock",
    "revenantscholar_test_common::mocks::account::SnakeAccountMock",
    "revenantscholar_test_common::mocks::account::SnakeEthAccountMock",
    "revenantscholar_test_common::mocks::erc20::DualCaseERC20Mock",
    "revenantscholar_test_common::mocks::erc20::SnakeERC20Mock",
    "revenantscholar_test_common::mocks::erc721::SnakeERC721Mock",
    "revenantscholar_test_common::mocks::erc721::DualCaseERC721ReceiverMock",
    "revenantscholar_test_common::mocks::erc1155::DualCaseERC1155ReceiverMock",
    "revenantscholar_test_common::mocks::erc1155::SnakeERC1155Mock",
    "revenantscholar_test_common::mocks::src5::SRC5Mock",
    "revenantscholar_test_common::mocks::non_implementing::NonImplementingMock",
]
