[package]
name = "revenantscholar_governance"
readme = "README.md"
keywords = [
    "openzeppelin",
    "starknet",
    "contracts",
    "standards",
    "governance"
]
version.workspace = true
edition.workspace = true
cairo-version.workspace = true
scarb-version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
repository.workspace = true
license-file.workspace = true

[tool]
fmt.workspace = true

[dependencies]
starknet.workspace = true
revenantscholar_access = { path = "../access" }
revenantscholar_introspection = { path = "../introspection" }
revenantscholar_account = { path = "../account" }
revenantscholar_token = { path= "../token" }

[dev-dependencies]
assert_macros.workspace = true
snforge_std.workspace = true
revenantscholar_utils = { path = "../utils" }
revenantscholar_testing = { path = "../testing" }
revenantscholar_test_common = { path = "../test_common" }

[lib]

[[target.starknet-contract]]
allowed-libfuncs-list.name = "experimental"
sierra = true
casm = false

[[test]]
name = "revenantscholar_governance_unittest"
build-external-contracts = [
    "revenantscholar_test_common::mocks::account::SnakeAccountMock",
    "revenantscholar_test_common::mocks::timelock::TimelockControllerMock",
    "revenantscholar_test_common::mocks::timelock::MockContract",
    "revenantscholar_test_common::mocks::timelock::TimelockAttackerMock",
    "revenantscholar_test_common::mocks::multisig::MultisigTargetMock",
    "revenantscholar_test_common::mocks::votes::ERC721VotesMock",
    "revenantscholar_test_common::mocks::votes::ERC20VotesMock"
]
